name: Sync all branches with master branch in same repository
on:
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 2147483647
    - name: Check remote
      run: git remote -v
    - name: Setup github ssh-key and execute script
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${DEPLOY_KEY}"
        scripts/sync_all_branches_with_master.sh
