name: Sync all branches with master branch in same repository
on:
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Sync all branches
      uses: repo-sync/github-sync@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      with:
        source_repo: "git@github.com:maxc0d3r/test-actions.git"
        source_branch: "master"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
